# 0. PCA UK YIELD CURVE:  A "2 FACTOR" MODEL OF ALL SPOT RATES

This notebook is base on by Nathan Thomas's notebook published in:
https://towardsdatascience.com/applying-pca-to-the-yield-curve-4d2023e555b3
which we have commented and extended.

We are going to show how to apply PCA to the yield curve of the UK.
We will show that the first and second principal component transforms 
(what we have been calling the tranformed "Z1" and "Z2" features of  4.PCAInMoreDepth.pptx slides 25 to 32)
are "latent" or hidden feature (as per slide 37) that
drive the behavior of the spot rates as a whole and that
correspond closely to the 10 Year Spot Rate and the UK Inflation Rate.

# 1. Import and clean data

First we import the spot rates at different maturities from 6 months to 10 years (20 rates=features in columns).

In [50]:

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

# Import Bank of England spot curve data from excel
df = pd.read_csv("indu_dly.csv", 
                   index_col=0)

df.head(20)

CSCO        DIS        XOM  ...       MSFT       INTC        CAT
Date                                        ...                                 
1/2/2008   20.984388  27.342632  67.229462  ...  26.874113  17.842361  49.893444
1/3/2008   21.150425  27.282520  67.459534  ...  26.988579  17.363743  49.716854
1/4/2008   20.652304  26.732916  66.201355  ...  26.233160  15.956061  48.409992
1/7/2008   20.660210  26.758680  65.583069  ...  26.408663  16.103865  48.551277
1/8/2008   20.106749  26.226250  64.741875  ...  25.523544  15.667488  47.435162
1/9/2008   20.747189  25.899933  65.827492  ...  26.278934  16.012363  47.491676
1/10/2008  20.747189  26.337894  65.899414  ...  26.195017  15.864564  47.618793
1/11/2008  20.454641  26.037329  64.921638  ...  25.874537  15.477448  46.629860
1/14/2008  20.786722  26.063087  65.302650  ...  26.240786  16.244637  47.519909
1/15/2008  20.438824  25.633717  64.001366  ...  25.943209  15.970139  46.198952
1/16/2008  19.885353  25.616539  62.211140  ...  25.355673  13.992352  45.400703
1/17/2008  19.237007  24.706264  60.327526  ...  25.264105  13.605236  44.377739
1/18/2008  19.213287  24.482990  61.168682  ...  25.187805  13.372966  44.619282
1/22/2008  18.564936  24.148077  59.277840  ...  24.386620  13.098468  45.336769
1/23/2008  18.999805  24.491575  59.996765  ...  24.363728  14.062728  46.231850
1/24/2008  19.853729  25.101286  61.830097  ...  25.370939  14.562455  46.352619
1/25/2008  19.134226  24.628977  60.349083  ...  25.134390  14.076806  46.835686
1/28/2008  19.055155  25.221519  61.204617  ...  24.966524  14.280916  48.455353
1/29/2008  19.023529  24.732025  61.168682  ...  24.874954  14.428731  49.009468
1/30/2008  19.260729  25.255865  61.312469  ...  24.569750  14.562455  48.618744

[20 rows x 28 columns]

In [51]:
# Drop nan values
df = df.dropna(how="any")

In [52]:
df.head()

CSCO        DIS        XOM  ...       MSFT       INTC        CAT
Date                                       ...                                 
1/2/2008  20.984388  27.342632  67.229462  ...  26.874113  17.842361  49.893444
1/3/2008  21.150425  27.282520  67.459534  ...  26.988579  17.363743  49.716854
1/4/2008  20.652304  26.732916  66.201355  ...  26.233160  15.956061  48.409992
1/7/2008  20.660210  26.758680  65.583069  ...  26.408663  16.103865  48.551277
1/8/2008  20.106749  26.226250  64.741875  ...  25.523544  15.667488  47.435162

[5 rows x 28 columns]

In [53]:
df = df.pct_change(periods = 1, fill_method = 'pad').fillna(0)
df.head()

CSCO       DIS       XOM  ...      MSFT      INTC       CAT
Date                                    ...                              
1/2/2008  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000
1/3/2008  0.007912 -0.002198  0.003422  ...  0.004259 -0.026825 -0.003539
1/4/2008 -0.023551 -0.020145 -0.018651  ... -0.027990 -0.081070 -0.026286
1/7/2008  0.000383  0.000964 -0.009339  ...  0.006690  0.009263  0.002919
1/8/2008 -0.026789 -0.019897 -0.012826  ... -0.033516 -0.027098 -0.022988

[5 rows x 28 columns]

# Assignment code:

In [38]:
from sklearn.decomposition import PCA
pca = PCA()
pca.fit(df)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [44]:
pca1_vec = pca.components_
pca1_val = pca.explained_variance_
print("eigenvectors:", pca.components_)
print("eigenvalues:", pca.explained_variance_)

eigenvectors: [[ 2.03719228e-01  2.06641638e-01  1.73781907e-01  1.95281520e-01
   1.95801634e-01  1.63117366e-01  1.86500328e-01  1.32984392e-01
   2.05211273e-01  1.06099069e-01  1.46525912e-01  1.08875660e-01
   1.75939879e-01  1.50845441e-01  3.26604765e-01  1.50399869e-01
   1.96664449e-01  1.09202189e-01  1.45752314e-01  9.78738340e-02
   2.87411042e-01  1.81236642e-01  1.85548794e-01  1.09779301e-01
   2.97261759e-01  1.85523075e-01  1.98151502e-01  2.34421393e-01]
 [-8.09442496e-02 -7.88344607e-02 -1.87346057e-01 -1.18024853e-01
  -2.11255006e-01 -7.45102778e-02 -1.41670972e-03 -8.73280332e-02
   2.17168402e-02 -1.30983466e-01 -5.21703978e-02 -1.13334725e-01
  -6.50588338e-02 -1.30376905e-01  6.05239407e-01 -1.79667798e-01
  -1.79087359e-01 -1.41874015e-01 -1.10102130e-01 -1.13087020e-01
   4.49849053e-01 -5.90111290e-02 -9.59156578e-02 -1.04407895e-01
   3.05700472e-01 -1.30757260e-01 -9.85319284e-02 -6.36984260e-02]
 [-2.34371526e-01 -1.32873990e-02 -2.02432178e-02 -7.9039829

In [81]:
proj = pca.transform(df)
pc1_proj = proj[:,0]
print(pc1_proj)

[-0.00278049 -0.01714361 -0.12467995 ... -0.03511155 -0.00619676
 -0.01883786]


In [67]:
df2 = pd.read_csv("indu_index_dly.csv", 
                   index_col=0)
indu_index = df2.pct_change(periods = 1, fill_method = 'pad').fillna(0)

indu_index.head(20)

^DJI
Date                
2008-01-02  0.000000
2008-01-03  0.000978
2008-01-04 -0.019648
2008-01-07  0.002134
2008-01-08 -0.018587
2008-01-09  0.011616
2008-01-10  0.009248
2008-01-11 -0.019201
2008-01-14  0.013632
2008-01-15 -0.021681
2008-01-16 -0.002796
2008-01-17 -0.024623
2008-01-18 -0.004927
2008-01-22 -0.010588
2008-01-23  0.024975
2008-01-24  0.008838
2008-01-25 -0.013850
2008-01-28  0.014477
2008-01-29  0.007785
2008-01-30 -0.003002

In [68]:
correlation = np.corrcoef(pc1_proj, indu_index['^DJI'])
print(correlation)

[[1.         0.98062386]
 [0.98062386 1.        ]]


In [87]:
'''Calculate the explained variance (in percent) of the first eigenvector (1).
Working backwards from the all principal component projections,
calculate their covariance matrix, and 
calculate the variance (in percent) of the first component projection (2).
(1) and (2) should be the same.'''
explained_variance = pca1_val[0]
print('explained variance first vector:', explained_variance)
principal_component_projections = pd.DataFrame(proj)
print('variance:', pc1_proj.var())
principal_component_projections.corr()


explained variance first vector: 0.004923951155053203
variance: 0.0049217791430748


0             1   ...            26            27
0   1.000000e+00  2.772190e-14  ...  1.956990e-16  2.533328e-16
1   2.772190e-14  1.000000e+00  ... -2.033778e-17  3.736979e-16
2  -1.636660e-16 -2.298452e-16  ... -1.147660e-16  6.565744e-16
3   2.566861e-16 -1.009676e-17  ...  3.832500e-16 -5.927563e-16
4  -1.068315e-16 -3.395331e-16  ...  7.250356e-16  3.808667e-17
5   1.970370e-16  1.138713e-17  ... -3.613952e-16  2.377092e-16
6   5.839056e-16  4.580247e-16  ...  5.149602e-16 -1.247457e-16
7  -3.944198e-16 -2.304086e-16  ...  2.085916e-16 -8.543069e-17
8  -6.935713e-16 -9.357598e-18  ...  1.937271e-16  1.005939e-16
9  -2.497058e-16  1.768762e-16  ...  2.337720e-16 -1.838292e-16
10 -7.589786e-17  4.282363e-17  ...  2.467454e-17  2.709897e-16
11 -7.799038e-18 -1.275678e-16  ... -6.637448e-16 -3.226691e-17
12 -4.437187e-16 -2.440464e-16  ... -1.516118e-16 -4.880838e-16
13  2.626346e-16  5.841096e-17  ... -3.897459e-16 -9.836975e-17
14 -1.245223e-16  1.385113e-16  ...  1.113495e-16  4.247734e-16
15  1.729557e-17 -2.157036e-16  ... -2.207855e-16 -6.551309e-16
16  1.413365e-15 -2.717818e-16  ...  1.930267e-16 -2.631316e-16
17 -4.776721e-16  5.467945e-16  ... -1.163531e-17  7.995957e-16
18  5.306129e-16 -3.153747e-16  ...  2.974797e-16 -3.562218e-16
19  5.327313e-16 -8.329304e-17  ... -1.085373e-16 -7.503519e-16
20 -3.795667e-16  1.752422e-16  ...  9.155879e-16 -1.610567e-15
21 -2.924942e-16  5.057966e-17  ...  8.785472e-17 -3.779854e-16
22  3.728847e-17  4.027474e-16  ...  1.322831e-16 -1.923980e-15
23  5.216391e-17 -1.330040e-16  ... -2.906129e-16  1.779539e-16
24  1.001573e-16  1.938820e-16  ...  1.121509e-17  2.892410e-16
25  7.250758e-17  8.264728e-17  ... -1.385739e-15 -9.021650e-16
26  1.956990e-16 -2.033778e-17  ...  1.000000e+00  3.212257e-16
27  2.533328e-16  3.736979e-16  ...  3.212257e-16  1.000000e+00

[28 rows x 28 columns]

In [77]:
#beta
from sklearn.linear_model import LinearRegression
betas_by_regression = []
for col in df.columns:
  X = pc1_proj.reshape(-1,1)
  lr = LinearRegression()
  y = df[col]
  reg = lr.fit(X,y)
  betas_by_regression.append(reg.coef_)
betas_by_regression

[array([0.20371923]),
 array([0.20664164]),
 array([0.17378191]),
 array([0.19528152]),
 array([0.19580163]),
 array([0.16311737]),
 array([0.18650033]),
 array([0.13298439]),
 array([0.20521127]),
 array([0.10609907]),
 array([0.14652591]),
 array([0.10887566]),
 array([0.17593988]),
 array([0.15084544]),
 array([0.32660477]),
 array([0.15039987]),
 array([0.19666445]),
 array([0.10920219]),
 array([0.14575231]),
 array([0.09787383]),
 array([0.28741104]),
 array([0.18123664]),
 array([0.18554879]),
 array([0.1097793]),
 array([0.29726176]),
 array([0.18552308]),
 array([0.1981515]),
 array([0.23442139])]

In [80]:
betas_by_pc1_eigenvector = pca1_vec[0]
print(betas_by_pc1_eigenvector)

[0.20371923 0.20664164 0.17378191 0.19528152 0.19580163 0.16311737
 0.18650033 0.13298439 0.20521127 0.10609907 0.14652591 0.10887566
 0.17593988 0.15084544 0.32660477 0.15039987 0.19666445 0.10920219
 0.14575231 0.09787383 0.28741104 0.18123664 0.18554879 0.1097793
 0.29726176 0.18552308 0.1981515  0.23442139]


# Sample Code:

We examine the correlation of the 20 rates. 
As you can see, the correlation among the rates is very high, 
signifying that there may be one or two major underlying features driving the entire system of rates over time.

In [ ]:
df.corr()

We will now standardize the 20 rates by subtracting the mean and dividing by the standard deviation.
This standardization prevents a situation where 
a given rate winds up as a protagonist of our PCA analysis simply 
because the series happens to be have markedly higher levels than the other series with which it is compared.

In [ ]:
# Standardise the data in the df into z scores
#df_std = ((df-df.mean()) / df.std())
#df_std.head()

We will now apply the np.cov (covariance) function to the 20 standardized rates
to calculate the covariance matrix but 
since the 20 rates are standardized
the calculation of the covariance matrix yields the correlation matrix.
To perform PCA: 
We will use the correlation matrix as input to the function np.linalg.eig.
We could instead skip the calculation of the covariance/correlation matrix
and apply sklearn.decomposition.PCA to the standardized rates (df_std) directly.
Both approaches give the same result.

In [49]:
# Create a covariance matrix 

corr_matrix_array = np.array(np.cov(df_std, rowvar=False))

## 2. Compute the eigenvalues & eigenvectors of the correlation matrix

In [ ]:
# Perform eigendecomposition

eigenvalues, eigenvectors = np.linalg.eig(corr_matrix_array)

# Put data into a DataFrame and save to excel
df_eigval = pd.DataFrame({"Eigenvalues":eigenvalues}, index=range(1,21))

df_eigval.to_excel("df_eigval.xlsx")
eigenvalues

In [ ]:
# Save output to Excel
df_eigvec = pd.DataFrame(eigenvectors, index=range(1,21))

df_eigvec.to_excel("df_eigvec.xlsx")
eigenvectors[0]

We will now calculate the proportion of variance explained by each eigenvector 
using as input the eigenvalues calculated by  np.linalg.eig

In [ ]:
# Work out explained proportion 
df_eigval["Explained proportion"] = df_eigval["Eigenvalues"] / np.sum(df_eigval["Eigenvalues"])

#Format as percentage
df_eigval.style.format({"Explained proportion": "{:.2%}"})


# sample:PCA projections 

We now calculate the PCA projections (or
what we have been calling the tranformed "Z" features of  4.PCAInMoreDepth.pptx slides 25 to 32).
These are "latent" or hidden feature (as per slide 37) that
drive the movement of the rates as a whole.
The most important is these Z features is Z1,
the one with the highest eigenvalue of 19.660842 
corresponding to an explained variance proportion of 98.30%.
We are going to select this feature by calling upon
principal_components[0] below and plotting it.
When we plot the first principal component, 
we can see that it looks very similar 
to the history of the 10-year maturity spot rate.

In [ ]:
principal_components = df_std.dot(eigenvectors)
principal_components.head()

In [ ]:
#plt.style.use('ggplot')
ax = plt.figure(figsize=(9,5))
ax = plt.plot(principal_components[0])
ax = plt.title("First Principal Component")

In [ ]:
df_10 = pd.DataFrame(df.iloc[:, [19]].values, columns=['10Y-Rate'], index = df.index)
ax = df_10.plot(y='10Y-Rate', legend=False)
ax = plt.title("10Y Spot Rate")
ax = plt.figure(figsize=(9,5))

The second principal component, Z2, is 
the one with the second highest eigenvalue of 0.309852 
corresponding to an explained variance proportion of 1.55%.
The up and down movements of this second principal hidden or latent Z feature 
correspond closely to the up and down movements of the UK inflation rate that
we plot below, and with which it is highly correlated (pearson corr =0.95856134).
The UK inflation rate is approximated as the difference 
between the rates of two different maturity spot rates: 10Y-2Y.

In [ ]:
# Calaculate 10Y-2Y slope

df_s = pd.DataFrame(data = df)
df_s = df_s[[2,10]]
df_s["slope"] = df_s[10] - df_s[2]
df_s.head()

In [ ]:
ax = df_s.plot(y="slope", legend=False)
ax = plt.title("10Y - 2Y slope")
ax = plt.figure(figsize=(9,5))

In [ ]:
np.corrcoef(principal_components[1], df_s["slope"])

We call this a "two factor" model of all spot rates,
with the 10-year spot rate and the
UK inflation rate as the underlying driving forces.

These results make sense. Remember that as per pca_yield_curve_INTRO.ipynb: 
The first eigenvector and principal component has been identified as the TSIR sensitivity to changes in yield curve level,
the second eigenvector and principal component has been identified as the TSIR sensitivity to changes in yield curve slope,
the third eigenvector and principal component has been identified as the TSIR sensitivity to changes in yield curve curvature.
The results of this notebook confirm this finding because:
The changes in yield curve level are closely tracked by the changes in the level of the 10 Year Spot Rate.
The changes in the yield curve slope are closely tracked by the changes in the Inflation Rate.

# sample: PCA projections: eigenvalue calculation by hand

It is possible to calculate the eigenvectors (and the associated explained variance)
by working backwards from the PCA projected Z features.
The eigenvectors appear as the diagonal elements of the Z features covariance matrix.
So:
1.966084e+01 is the first eigenvalue 19.66084,
3.098525e-01 is the second eigenvalue 0.309852,
etc.
To calculate the sum of the diagonal, use np.trace()

In [ ]:
principal_components.cov()